# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ok Zoomer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ok Zoomer
  pod 'Firebase/Analytics'

  target 'Ok ZoomerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ok ZoomerUITests' do
    # Pods for testing
  end

end
